//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtistCRM.ModelHome
{
    using ArtistCRM.Model;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtistCRMEntities : DbContext
    {
        public ArtistCRMEntities()
            : base("name=ArtistCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Track> Track { get; set; }
        public virtual DbSet<TrackStatistics> TrackStatistics { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
