//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtistCRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int ProfileID { get; set; }
        public int UserID { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string Biography { get; set; }
    
        public virtual User User { get; set; }
    }
}
