//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtistCRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackStatistics
    {
        public int StatisticID { get; set; }
        public int Listens { get; set; }
        public int Likes { get; set; }


        public int TrackID { get; set; }
        public virtual Track Track { get; set; }
    }
}
