//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtistCRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public Track()
        {
            this.TrackStatistics = new HashSet<TrackStatistics>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Artist { get; set; }
        public System.TimeSpan Duration { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Genre { get; set; }
        public virtual ICollection<TrackStatistics> TrackStatistics { get; set; }
    }
}
